---
rules:
  braces:
    forbid: true
  brackets:
    forbid: true
  colons:
    max-spaces-after: 1
    max-spaces-before: 0
  commas:
    max-spaces-after: 1
    max-spaces-before: 0
    min-spaces-after: 1
  comments:
    ignore-shebangs: true
    level: warning
    min-spaces-from-content: 2
    require-starting-space: true
  comments-indentation: enable
  document-end:
    present: true
  document-start:
    present: true
  empty-lines:
    max: 1
    max-end: 0
    max-start: 0
  empty-values: disable
  hyphens:
    max-spaces-after: 1
  indentation:
    check-multi-line-strings: true
    indent-sequences: consistent
    spaces: 2
  key-duplicates: enable
  key-ordering: enable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  octal-values: disable
  quoted-strings:
    quote-type: single
    required: only-when-needed
  trailing-spaces: enable
  truthy:
    level: warning
yaml-files:
  - '*.yaml'
  - '*.yml'
  - .yamllint
...
