---
services:
  container-hosts:
    build: .
    container_name: container-hosts
    environment:
      - TZ=Europe/Berlin
      - HOST_IP4=192.168.178.5
      - HOST_IP6=fd00::94c6:91aa:9ced
    restart: unless-stopped
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

version: '3.5'
volumes:
  data: null
...
